Run Suite|Debug Suite|Load in Interactive Console
*** SEttings ***
Library   RPA.Email.ImapSmtp    smtp_server=smtp-mail.outlook.com smt_port=587  
Task Setup    Authorize    account=%{EMAIL}   password=%{PASSWORD}


*** Variables ***


*** Tasks ***
Sending email
   Send Message  sender=%{EMAIL}  
   ...    recipients=destination@mail.com
   ...    subject=Robot message
   ...    body=Message generated by robot
   ...    attachments=AutomationExample.xlsx
